# Generated by Django 2.2.4 on 2021-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sgs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgs',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='exporterCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='exporterCompanyAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='importCompanyAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='importerCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='invoiceNoDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgs',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
